### ISSUE TITLE
Ark Api Does not detect Version

### ISSUE THREAD

**Issue by randycarrero** [TBro98/QTBroArkApiManager_ServerPlugins#1]
![API error](https://user-images.githubusercontent.com/15186165/128952026-87f77e5d-635f-46bc-b8f9-e2254e1d79cf.PNG)

the program does not detect the version you have installed.
Also does not pick up on the plugins you have installed already.

**Comment by TBro98** [comment]
> ![API error](https://user-images.githubusercontent.com/15186165/128952026-87f77e5d-635f-46bc-b8f9-e2254e1d79cf.PNG)
> 
> 程序无法检测到您已安装的版本。
> 也不会拿起你已经安装的插件。

Because the arkapi version is built into .dll,it is difficult to get.So i set a version.json just like PluginInfo.json to save arkapi version.
you can try "Update ArkApi".

"The Plugins Already Download" is not from servers,in "Servers List" 
![QQ图片20210811131320](https://user-images.githubusercontent.com/64695777/128973165-e28f0710-9ee5-411d-b5dc-3185c4993d48.png)

**Comment by randycarrero** [comment]
I Understand
